version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - vinylvault-network

  backend:
    image: vinylvault-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - VINYLVAULT_DATABASE_URL=postgres://vinylvault:vinylvault@postgres:5432/vinylvault?sslmode=disable
    networks:
      - vinylvault-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: vinylvault
      POSTGRES_USER: vinylvault
      POSTGRES_PASSWORD: vinylvault
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vinylvault-network

networks:
  vinylvault-network:
    driver: bridge

volumes:
  postgres_data: